### ISSUE TITLE
CI Logon auth token not updating in MEICAN production

### ISSUE THREAD

**Issue by usmanazFIU** [atlanticwave-sdx/sdx-meican#49]
The auth token in the table ci-logon-auth does not gets updated. therefore user is not redirected to the SDX-circuit-create page

**Comment by mahidhar1g** [comment]
This is the test case template for the issue.

[Topology Mapping Test.xlsx](https://github.com/user-attachments/files/15745835/Topology.Mapping.Test.xlsx)

**Comment by mahidhar1g** [comment]
**Getting this response from the curl request -** {"error":"unauthorized_client","error_description":"incorrect secret"}

**The curl request -** 
curl_setopt_array($curl, array(
        CURLOPT_URL => '[https://cilogon.org/oauth2/token?grant_type=authorization_code&client_id=cilogon%3A%2Fclient_id%2F'.$CILogonClientID.'&redirect_uri=https%3A%2F%2F'.$meican_url.'%2Fcircuits%2Fnodes%2Fshow&client_secret=Vib4sbOGQXI8tt9s-uQ16hQnJlNUxUsAvAMISiCJBPFlLf2c82ZyUDKBYpv-eNX6qV-wW-OzRzoAaVslxCsozQ&code='.$code.'](https://cilogon.org/oauth2/token?grant_type=authorization_code&client_id=cilogon%3A%2Fclient_id%2F%27.$CILogonClientID.%27&redirect_uri=https%3A%2F%2F%27.$meican_url.%27%2Fcircuits%2Fnodes%2Fshow&client_secret=Vib4sbOGQXI8tt9s-uQ16hQnJlNUxUsAvAMISiCJBPFlLf2c82ZyUDKBYpv-eNX6qV-wW-OzRzoAaVslxCsozQ&code=%27.$code.%27)',
        CURLOPT_RETURNTRANSFER => true,
        CURLOPT_ENCODING => '',
        CURLOPT_MAXREDIRS => 10,
        CURLOPT_TIMEOUT => 0,
        CURLOPT_FOLLOWLOCATION => true,
        CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
        CURLOPT_CUSTOMREQUEST => 'GET',
       ));

These are the variables defined in the above curl request for CURLOPT_URL

**clientid -** "605df2dd7439b322db8d20f75d542f3c"
**Meican url -**  "67.17.206.206"
**code -** "NB2HI4DTHIXS6Y3JNRXWO33OFZXXEZZPN5QXK5DIGIXTMMTFHAYDAODDGA4DQMZVGU4DQNDGHAYGKMZTGE3DSMZQGI4GMNB7OR4XAZJ5MF2XI2D2I5ZGC3TUEZ2HGPJRG4YTQMBUGY4DKOBVHE3CM5TFOJZWS33OHV3DELRQEZWGSZTFORUW2ZJ5HEYDAMBQGA"


Here since the access token is not getting generated, that's why we are redirecting to that Cilogon page again and again.
